let yOffset = 0; // window.pageYOffset 대신 쓸 변수
let currentScene = 0; // 현재 활성화된(눈 앞에 보고있는) 씬(scroll-section)

const sceneInfo = [
  {
    // 0
    heightCnt: 5, // 브라우저 높이의 5배로 scrollHeight 세팅
    scrollHeight: 0,
    imgCount: 117,
    objs: {
      container: document.querySelector("#scroll-section-0"),
      messageA: document.querySelector("#scroll-section-0 .main-msg.a"),
      messageB: document.querySelector("#scroll-section-0 .main-msg.b"),
      messageC: document.querySelector("#scroll-section-0 .main-msg.c"),
      messageD: document.querySelector("#scroll-section-0 .main-msg.d"),
      canvas: document.querySelector("#canvas-0"),
      context: document.querySelector("#canvas-0").getContext("2d"),
      videoImages: [],
    },
    values: {
      images_seq: [0, 116],
      canvas_opacity: [1, 0, { start: 0.9, end: 1 }],
      messageA_opacity_in: [0, 1, { start: 0.1, end: 0.2 }],
      messageB_opacity_in: [0, 1, { start: 0.3, end: 0.4 }],
      messageC_opacity_in: [0, 1, { start: 0.5, end: 0.6 }],
      messageD_opacity_in: [0, 1, { start: 0.7, end: 0.8 }],
      messageA_translateY_in: [20, 0, { start: 0.1, end: 0.2 }],
      messageB_translateY_in: [20, 0, { start: 0.3, end: 0.4 }],
      messageC_translateY_in: [20, 0, { start: 0.5, end: 0.6 }],
      messageD_translateY_in: [20, 0, { start: 0.7, end: 0.8 }],
      messageA_opacity_out: [1, 0, { start: 0.25, end: 0.3 }],
      messageB_opacity_out: [1, 0, { start: 0.45, end: 0.5 }],
      messageC_opacity_out: [1, 0, { start: 0.65, end: 0.7 }],
      messageD_opacity_out: [1, 0, { start: 0.85, end: 0.9 }],
      messageA_translateY_out: [0, -20, { start: 0.25, end: 0.3 }],
      messageB_translateY_out: [0, -20, { start: 0.45, end: 0.5 }],
      messageC_translateY_out: [0, -20, { start: 0.65, end: 0.7 }],
      messageD_translateY_out: [0, -20, { start: 0.85, end: 0.9 }],
    },
  },
  {
    // 1
    heightCnt: 1,
    scrollHeight: 0,
    imgCount: 0,
    objs: {
      container: document.querySelector("#scroll-section-1"),
      content: document.querySelector("#scroll-section-1 .desc"),
    },
  },
  {
    // 2
    heightCnt: 4,
    scrollHeight: 0,
    imgCount: 117,
    objs: {
      container: document.querySelector("#scroll-section-2"),
      messageA: document.querySelector("#scroll-section-2 .a"),
      messageB: document.querySelector("#scroll-section-2 .b"),
      messageC: document.querySelector("#scroll-section-2 .c"),
      pinB: document.querySelector("#scroll-section-2 .b .pin"),
      pinC: document.querySelector("#scroll-section-2 .c .pin"),
      canvas: document.querySelector("#canvas-2"),
      context: document.querySelector("#canvas-2").getContext("2d"),
      videoImages: [],
    },
    values: {
      images_seq: [0, 116],
      canvas_opacity_in: [0, 1, { start: 0, end: 0.1 }],
      canvas_opacity_out: [1, 0, { start: 0.95, end: 1 }],
      messageA_translateY_in: [20, 0, { start: 0.15, end: 0.2 }],
      messageB_translateY_in: [30, 0, { start: 0.5, end: 0.55 }],
      messageC_translateY_in: [30, 0, { start: 0.72, end: 0.77 }],
      messageA_opacity_in: [0, 1, { start: 0.15, end: 0.2 }],
      messageB_opacity_in: [0, 1, { start: 0.5, end: 0.55 }],
      messageC_opacity_in: [0, 1, { start: 0.72, end: 0.77 }],
      messageA_translateY_out: [0, -20, { start: 0.3, end: 0.35 }],
      messageB_translateY_out: [0, -20, { start: 0.58, end: 0.63 }],
      messageC_translateY_out: [0, -20, { start: 0.85, end: 0.9 }],
      messageA_opacity_out: [1, 0, { start: 0.3, end: 0.35 }],
      messageB_opacity_out: [1, 0, { start: 0.58, end: 0.63 }],
      messageC_opacity_out: [1, 0, { start: 0.85, end: 0.9 }],
      pinB_scaleY: [0.5, 1, { start: 0.5, end: 0.55 }],
      pinC_scaleY: [0.5, 1, { start: 0.72, end: 0.77 }],
      pinB_opacity_in: [0, 1, { start: 0.5, end: 0.55 }],
      pinC_opacity_in: [0, 1, { start: 0.72, end: 0.77 }],
      pinB_opacity_out: [1, 0, { start: 0.58, end: 0.63 }],
      pinC_opacity_out: [1, 0, { start: 0.85, end: 0.9 }],
    },
  },
  {
    // 3
    heightCnt: 5,
    scrollHeight: 0,
    imgCount: 2,
    objs: {
      container: document.querySelector("#scroll-section-3"),
      canvasCaption: document.querySelector(".canvas-caption"),
      canvas: document.querySelector("#canvas-3"),
      context: document.querySelector("#canvas-3").getContext("2d"),
      videoImages: [],
    },
    values: {
      images_seq: [0,1],
      rectL: [0, 0, { start: 0, end: 0 }],
      rectR: [0, 0, { start: 0, end: 0 }],
      blendHeight: [0, 0, { start: 0, end: 0 }],
      canvas_scale: [0, 0, { start: 0, end: 0 }],
      canvasCaption_opacity: [0, 1, { start: 0, end: 0 }],
      canvasCaption_translateY: [20, 0, { start: 0, end: 0 }],
      rectStartY: 0,
      canvasScaleRatio : 0,
    },
  },
];
